### ISSUE TITLE
Reposition caret when file saves, line trims

### ISSUE THREAD

**Issue by ccleaud** [Alexey-T/SynWrite#10]
When saving with trim trailing spaces enabled and "Allow caret after end of line" disabled , considering a line ending with some spaces and the caret at the end of this line, saving will not reposition the caret to the new end of line.
Thus, continuing typing re-inserts spaces before what the user types.
Tested on version: 6.21.2240

Thanks for fixing.

**Comment by Alexey-T** [comment]
Todo

**Comment by ccleaud** [comment]
Thanks!
By the way, your tool is just AWESOME !!! :) :) :)

**Comment by Alexey-T** [comment]
It is small bug of EControl,hard to fix here, can u report it to Michael? (save is doing in ECon)
