### ISSUE TITLE
Strange behavior with TAB key

### ISSUE THREAD

**Issue by ccleaud** [Alexey-T/SynWrite#12]
My TAB key is mapped to "Insert TAB character" (default behavior).

I noticed a different behavior with selected line and TAB key press:
- One selected line is NOT indentable using TAB key: the line is fully overwritten by a tab character.
- But if 2 lines or more are selected, everything is OK: they are all indented.

So, I don't really understand why this happened like this but I think one (case where only one) selected line must be indentable using TAB.

Thanks for considering this ticket.
Reagrds

**Comment by Alexey-T** [comment]
Seems not default for "tab" key is set; default is "Indents and tabs: Tab key", try it.
