### ISSUE TITLE
[ENHANCEMENT] - New options

### ISSUE THREAD

**Issue by ccleaud** [Alexey-T/SynWrite#14]
Can you add those useful features please:
- "open directory in explorer" (in right click of a tab and in file menu)
- "open directory in command prompt" (in right click of a tab and in file menu)
- "Copy to group" in right click of a tab
- "Delete file" in right click of a tab (already present in File menu)

Thanks
Best regards

**Comment by Alexey-T** [comment]
3) cannot: cannot COPY tabs
4) Delete, not good in rt-click menu 
1..2) You can make plugin for it
