### ISSUE TITLE
Mouse cursor is not different when moving and when copying text selection

### ISSUE THREAD

**Issue by ccleaud** [Alexey-T/SynWrite#15]
When drag-dropping selected text, the mouse cursor is the same even if CTRL key is pressed.
But, CTRL key, in such case, will copy text instead of moving it.

Can you change the mouse cursor and add a (+) in the add-left corner of the mouse cursor when copying text?
I hope this is not internal to EControl.ru...

Thanks
Regards

**Comment by Alexey-T** [comment]
-Can you change the mouse cursor
I see no addition to cursors here.So cannot use other cursor with +..
