### ISSUE TITLE
Del API actions?

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/SynWrite#22]
@kvichans Can i delete this IDs in app_prop()? Not used in any plugs from SF.net
SynWrite.
Other API can do it: ed_handles() etc

- `PROP_GROUP_INDEX` | R  | int | Index of active tab-group. 1-based.
- `PROP_GROUPS`      | R  | str | Count of tabs in each tab-group. It's ","-separated list of ints. "2,4,0," shows: "3 groups visible, 2 tabs in group1, 4 tabs in group2". "2,0,0,6," shows: "4 groups visible, 2 tabs in group1, 6 tabs in group4".
- `PROP_EDITOR_BY_INDEX` | R | int | Handle (pass it to `Editor()` to make object) of editor at given group-index and tab-index. `value` parameter must be 3 numbers ","-separated.  ..

**Comment by kvichans** [comment]
Bad idea! Not all plugings are published on SF.net
Dont break API.

**Comment by Alexey-T** [comment]
I will del inf on WIKI and make mark: deprecated
Later i will del these id

**Comment by kvichans** [comment]
Why? "Breaked API" is very bad

**Comment by Alexey-T** [comment]
Coz these IDs redundant (can do all in other api)
