### ISSUE TITLE
Sort plug

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/SynWrite#3]
Wish for @kvichans

вот такой дл в Сине-
![sort](https://cloud.githubusercontent.com/assets/4154978/15497821/9c64a7b4-21ad-11e6-86e0-7d923e2bd53a.png)

(и 2 кмд- sort asc/ desc)
 хочется выкинуть код и иметь плаг;
Чтобы облегчить Син
(Син 6.21 имеет dlg_custom)

**Comment by kvichans** [comment]
ToDo

**Comment by Alexey-T** [comment]
Нравится выкидывать паскаль-код(его трудно подд-ть, да и компилировать трудно)
