### ISSUE TITLE
Installing python addon in SynWrite ??

### ISSUE THREAD

**Issue by DerellLicht** [Alexey-T/SynWrite#30]
I have a first-pass prototype for the "backup to specified directory" addon, and I'm trying to install it.

I'm looking at TutorialPlugins1.odt which comes with your package.  It states the following:

"To call new plugin, just call ready menu item “Tools - Plugins - SynMyGoto”. "

However, there is no Plugins under Tools.  

There *is* a separate Plugins menu, but it doesn't have any option for running/installing/loading a plugin.

I looked at Options -> Addon Manager, but none of those options seem to actually work.
The Install option there, does not list my plugin.

I installed my plugin in:
C:\SynWrite\Plugins\SynStaticBackup
which is the subdirectory that I listed in install.inf

What do I *actually* need to do??
(BTW, you should probably review TutorialPlugins1.odt, seems to need some updates)

**Comment by Alexey-T** [comment]
You need zip file. zip file must have

- install.inf
- `__init__.py` with code
- folder `readme` with a) readme.txt, b) history.txt

zip all. Now in Synw, open this zip file like text file. Msg shows "install?"

**Comment by Alexey-T** [comment]
It will install to "py/syn_nnn". syn_nnn is word from ur install.inf.

**Comment by Alexey-T** [comment]
updated https://github.com/Alexey-T/SynWrite/blob/master/Readme/TutorialPlugins1.odt

**Comment by DerellLicht** [comment]
Okay, that seems to have worked, my addon shows up in Addon Manager -> Edit.
However, it doesn't do anything.  I'll post that as a separate issue, since this one is now successfully addressed!  Thank you!

**Comment by Alexey-T** [comment]
Pls make Gihhub repo "syn_nnnnnnnnnnn" for this plg, will download +test

**Comment by DerellLicht** [comment]
I'm assuming I should create this repo on *my* github page, true??  
That's what I'll do for now, anyway.

**Comment by DerellLicht** [comment]
https://github.com/DerellLicht/syn_static_backup.git

Currently, it backs up to c:\me2008\backup
Next, I need to make this user-configurable; probably use an INI file, probably use SynWrite_directory/backup as default location.
What mechanism should I use, to let user call up a config dialog and specify alternate save location?
Is it possible to hook into the existing Options/Configure (F9) dialog to handle this??

**Comment by Alexey-T** [comment]
You should use dlg_custom: inf is at Cuda page- http://wiki.freepascal.org/CudaText_API#dlg_custom

**Comment by Alexey-T** [comment]
Wrote msg at GH, of plugin (next msgs in it too)
