### ISSUE TITLE
Where are syntax-hiliting settings stored ??

### ISSUE THREAD

**Issue by DerellLicht** [Alexey-T/SynWrite#32]
Every time I update SynWrite, I lose all my syntax-hiliting settings.
I tried backing up the files in SynWrite\Settings, but none of those change after update.

**Comment by Alexey-T** [comment]
http://www.uvviewsoft.com/synwrite/files/help/SynWrite/
FAQ item- How to keep lexers settings on app reinstalling.

**Comment by DerellLicht** [comment]
Excellent!!  Thank you.
Sorry for not looking at the FAQ myself, I'll review the rest of them now.

**Comment by DerellLicht** [comment]
One more settings question:
How do I set the text color for the status bar ??
On my work machine, it appears to be Teal, which is almost invisible against the Deviant Dark background.
I don't see anything in the Themes/Colors list that specifies that color...

**Comment by Alexey-T** [comment]
I need to add "statusbar font" item, todo

**Comment by Alexey-T** [comment]
@DerellLicht It is colors in Deviant skin file, in the data/skins folder

**Comment by DerellLicht** [comment]
Aye, I get it now!!  Basicallly, [StatusBar] lacked a Normal.TextColor setting, which presumably defaults to System color.  I copied settings from [MenuBar] to [StatusBar], and thus everything is as I expected.

Could you clarify for me, what the various fields mean, though?
I think the 0 in Normal.Borders first param, means "don't draw this", but then why are the color arguments there?
Also, Why does Normal.Body have two color arguments?  That appears to just specify the background color for the field; two arguments seems redundant!!
BTW, is there a "comments" indicator in this file?  ; or # or something ??

[MenuBar]
Normal.Body=1, $00495342, $00657360
Normal.Borders=0, $003A3F31, $003A3F31
Normal.TextColor=$00CAD0C0

**Comment by Alexey-T** [comment]
How can i fix my skin files? diff.
