### ISSUE TITLE
cannot open cmdline param "dir/dir/filename.ext"

### ISSUE THREAD

**Issue by DerellLicht** [Alexey-T/SynWrite#35]
I'm on Windows 7, 32-bit (at work), and I'm experiencing an intermittent issue here.
My console is tcc/le 32-bit, within ConsoleZ.

I'm sitting in directory C:\SourceCode\kora_rel , and typed:
syn common\app\main.c
and got an error dialog: "File does not exist, create it?"
However, file *does* exist.
I can fix it by switching to forward slashes:
syn common/app/main.c
and the file loads just fine.

But why should the latter form even work?  I'm not running a linux-style shell.
Also, I *don't* always have this issue; in some cases, the relative path with backslashes works fine.

This isn't a major issue, but it *is* confusing!!  Any insights into what is going on?

**Comment by DerellLicht** [comment]
Actually, I have another issue with files that are loaded this way; running
syn common/app/main.c
results in the tab containing "common/app/main.c", rather than just "main.c", and thus does not fit on the tab.  This would *also* be solved by fitting the tab to the text, but it would be better if only the base filename was displayed...

**Comment by Alexey-T** [comment]
Reason is: SW dont support expanding short path dd\dd\dd.dd to full. with "dd.dd" maybe it does. with paths not.

**Comment by DerellLicht** [comment]
That's sad.  It greatly reduces the usability of the program from the console, which is how I typically work.
At my current job, most source files are in subdirectories.  I find them using find or its derivatives, which provide relative paths.

**Comment by Alexey-T** [comment]
Will try to fix it

**Comment by Alexey-T** [comment]
Im puzzled.I do in cmd.exe:

~~~
C:\Users\user>d:
D:\>cd arc\s
D:\Arc\S>syn tests\treetest\unit1.dfm
D:\Arc\S>
~~~
here Syn.exe opens unit1.dfm ok. How do u test, that error shows?

**Comment by Alexey-T** [comment]
>My console is tcc/le 32-bit, within ConsoleZ.

Try in cmd.exe pls

**Comment by DerellLicht** [comment]
Interesting... on Windows 7 64-bit, I get the same behavior as you.
Both cmd.exe and tccle (32-bit) show just the base filename, when I open a relative path.
So apparently this is a Windows 7 32-bit issue??  What a pain...

**Comment by Alexey-T** [comment]
found a trick/hack. Pls try http://uvviewsoft.com/bb/

**Comment by DerellLicht** [comment]
Yes!!!  That *does* appear to work!!!
Thank you for all your excellent support!  This is a superb editor...

**Comment by Alexey-T** [comment]
Okay; can you make a review at http://www.softpedia.com/get/Programming/File-Editors/Syn2.shtml#disqus_thread ?

**Comment by DerellLicht** [comment]
It is done !!
