### ISSUE TITLE
feature request: text search - show all ?

### ISSUE THREAD

**Issue by DerellLicht** [Alexey-T/SynWrite#37]
This is a feature that has been present in other editors, and is *very* useful in many cases.
right now, in SynWrite, I can *count* all occurrences, but I have to just look at each one, one at a time.
When searching source code for a target, it is often useful to be able to get a list of all instances of that target, then select which I wish to visit.

What would it take to implement this in SynWrite?  At a minimum, I would accept having the list dumped to the Output window, with line numbers shown.  Even better would be if I could double-click on a line in the results window, and have that move the cursor to that line in the file window.

Please comment on what this would require??

**Comment by Alexey-T** [comment]
@kvichans You plan to do Find plugins for SW. Maybe you can do this wish? Cudatext has it?

**Comment by DerellLicht** [comment]
Okay, I'll look at this.  I'd be happy to get more skilled at SynWrite addons.

Do you have an existing guide to making cudatext available in SynWrite builds?  You recently gave me another suggestion to look at, which required cudatext, but I didn't have that package available.  When I tried to find how to install it, all I could find was the full editor, which presumably is not what I want?

**Comment by Alexey-T** [comment]
CudaText is another editor. I use it today, i not use SynWrite today

**Comment by DerellLicht** [comment]
I had looked at cudatext editor previously, and just reviewed it again now.  
I cannot say that I find it superior, or even close to equal, to SynWrite... most options need to be hacked in json files, rather than a comprehensible options-dialog environment.  I have no idea whether I can configure it to do all the excellent things that SynWrite already does, but I *know* I don't have time to work on it while I'm at work !!!

Is there some way to use CudaText plugins in SynWrite ??

**Comment by Alexey-T** [comment]
@kvichans Wants to port FindInFiles to Synwrite from Cudatext. not easy change..

**Comment by Alexey-T** [comment]
You may ask which things u cannot do in Cudatext. I can do most things

**Comment by DerellLicht** [comment]
Okay, I'll make a quick attempt to make CT usable for me, make it work the way SW works.

1. no Deviant Dark theme; don't really like the existing CT themes, though there are a couple of dark themes that I could live with.
2. tried setting custom colors in the lexer, for .C files; my colors are all there in the Lexer Properties window, but they are not used by my actual main.c file.
3. How to use numbered bookmarks??  SW uses semi-standard "Ctrl-Shift-N for Set, Ctrl-N for Goto", don't know what, if any, CT uses; can't find keyboard commands at all
4. keystroke macros ??  SW is very intuitive in use, CT doesn't appear to have it at all, maybe it's hidden in a JSON file somewhere?
5. hotkeys - clicked on the menu item, got a dialog that says "To customize hotkeys, call Commands dialog, focus any command, and press F9, you'll see additional dialog".  However... I don't see any option for a Commands dialog at all.

That's all I have time for now, haven't even *started* looking at the more subtle options, most of which SynWrite does easily.

**Comment by Alexey-T** [comment]
replied:
http://synwrite.sourceforge.net/forums/viewtopic.php?f=20&t=1743&p=10307#p10307

**Comment by DerellLicht** [comment]
Okay, sounds like with sufficient extra effort, I can make CD work as well as SW already does.

ITM, Does that mean you aren't going to be doing any further development (other than bug fixes, which you have dont *alot* of!!) on SynWrite??  How about @kvichans ??  It sounds, from your above post to him, that he's still working on SW ??

**Comment by Alexey-T** [comment]
He's moved from SW to Cud, made plugins for C..

**Comment by kvichans** [comment]
Hi, @DerellLicht, @Alexey-T.
I will plan to adapt CudaText FiF plugin for SynWrite at next week.

**Comment by kvichans** [comment]
@DerellLicht 
I worked in SynWrite more then two years. Now (from nov15) i work only in CudaText.

**Comment by DerellLicht** [comment]
Hi @kvichans !
Well, I appreciate your efforts to get last couple of implemented in SynWrite for me.  
At this point, I really don't find CudaText usable on the job, but SynWrite is very close.

**Comment by Alexey-T** [comment]
@DerellLicht Almost done plugin FindInFiles;
plugin ready at GH; and SYnw beta ready in uvviewsoft.com/bb/

**Comment by DerellLicht** [comment]
Well, that *does* appear to work!!  In fact, it goes beyond what I was asking for, showing results for *all* tabs, I just wanted all results for current tab.  But that works fine!!  I thank you very much for your efforts...

**Comment by Alexey-T** [comment]
@DerellLicht If Plugins menu-it has command to find in One tab or all tabs. Can u test it, its ok?

**Comment by Alexey-T** [comment]
What features of Find of Synwrite not done. I want to deleted builtin FindInFiles

**Comment by DerellLicht** [comment]
Hi Alexey-T;
I don't know what you mean about command in "Plugins menu" .... the Plugins menu at top of program doesn't have *any* reference to File Find, that I can see.

I use Ctrl-F for search/find; the search dialog now has a "Find in all tabs" button, which is what I tested.  I don't see any "Find in current tab" button.  Should I see such an option?

However, I didn't do a clean install for the beta version that I got from your bb directory; I just un-zipped the SynWrite.zip file over my existing installation.  Was that the wrong way to do things?

**Comment by Alexey-T** [comment]
hm.You didnt install plugin. Wait a day. will be in AddonManager

**Comment by DerellLicht** [comment]
I guess it's been awhile since I used SynWrite !!  I thought all I needed to do was put the plugin in Synwrite\Py\syn_find_in_files, then restart SynWrite.  That *does* appear to have add the button that I mentioned, to the Search dialog...

**Comment by Alexey-T** [comment]
Pls open this .zip in Synw- then Plugins menu/ findinfiles
[syn_find_in_files-master.zip](https://github.com/Alexey-T/SynWrite/files/766864/syn_find_in_files-master.zip)

**Comment by Alexey-T** [comment]
![fif](https://cloud.githubusercontent.com/assets/4154978/22829095/3416643c-efba-11e6-94a3-28f3f4ae6095.png)

**Comment by DerellLicht** [comment]
Okay, I remember now.
Now I have looked at this new addon.  Opening the results in a new tab, though, is awkward because I cannot click on entries in the results tab, and thus make the cursor jump to that line in the source file.

I prefer the results from the "Find in All Tabs" button on the normal Search dialog; that works well !!
Where did that come from?  I don't remember seeing that when I was previously using SynWrite ??

**Comment by Alexey-T** [comment]
click in result dont work; DblClick will be here, in few days, todo

**Comment by Alexey-T** [comment]
plugin+Synw: released; pls next wishes, post at https://github.com/kvichans/syn_find_in_files
it's welcome

**Comment by DerellLicht** [comment]
umm... please clarify, did you leave the old find dialog in place, with the "Find in all tabs" button??  I hope so...

I have one other issue that interfered at last job, I'll leave in separate issue thread.

**Comment by Alexey-T** [comment]
i keep dialog. But want to del it in next versions
