### ISSUE TITLE
How to use blanks to indent block for lexer?

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#45]
В разделе настроек `Insert/Format` стоит `Tab char` для `Tab mode`.
В разделе настроек `LexOverrides` для `Python` стоит `Spaces` для `Tab mode`.
- По Tab внутри строки вставляются пробелы.
- Но при сдвиге блока вставляются табуляторы 

Как настроить, чтобы блоки сдвигались пробелами только в Питоне?

**Comment by Alexey-T** [comment]
отключить опцию Optimal fill with tabs?

**Comment by kvichans** [comment]
Попробовал. Это не решение.
Одно исправилось: в py-файлах блок при сдвиге **стал** заполняться пробелами.
Другое испортилось: в остальных файлах блок при сдвиге **перестал** заполняться табуляторами

**Comment by Alexey-T** [comment]
подумал.
Решение - юзать OptimalFillWithTabs в оверрайде. BlockIndent тоже
