### ISSUE TITLE
(bug) dlg_custom - hidden controls

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#47]
![hid-ctrls](https://cloud.githubusercontent.com/assets/7419630/22701520/e6ec6000-ed6e-11e6-9b43-ff3babef24a5.PNG)
Репро (м.б. только на Win, только у меня):
- Клик ЛКМ по любой кнопке
- Нажать Alt

----
Должен быть такой вид
![all-ctrls](https://cloud.githubusercontent.com/assets/7419630/22701633/39d2db32-ed6f-11e6-9217-cf1c48c9f09a.PNG)

**Comment by Alexey-T** [comment]
как повторить то же, на плагине Explorer integration? делал фикс. давно. он работает в этом плг

**Comment by Alexey-T** [comment]
?
