### ISSUE TITLE
(bug, API) dlg_custom start focus

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#49]
[dlg_custom_ctrls.txt](https://github.com/Alexey-T/SynWrite/files/760518/dlg_custom_ctrls.txt)
Код 
```
import  sw as  app
app.dlg_custom("Find in Files (1.1.13)",759,117,open(r"dlg_custom_ctrls.txt").read(), 8)
```
ставит фокус на `.*`
![focus](https://cloud.githubusercontent.com/assets/7419630/22736445/347f4332-ee0f-11e6-93b8-d06717d14447.PNG)

А должен ставить на 8-ой контрол, то есть на сомбо правее `Find`.

**Comment by Alexey-T** [comment]
Это изза особености Делфи. поправлю

**Comment by Alexey-T** [comment]
fix
