### ISSUE TITLE
Create tab in group

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#51]
Нужен способ, чтобы создавать новый таб в конкретной группе.

 В Куд можно создать таб в нужной группе через
`  app.file_open(filename, group)`

**Comment by Alexey-T** [comment]
done; Beta

**Comment by kvichans** [comment]
Как реализовано? Где описано?
Раньше уже был второй параметр:
`file_open(filename, params='') 	Opens editor-tab for given file name. It activates already opened editor-tabs. Pass empty string for empty tab. params is optional: if it contains "/s", then installation of zip-filename will be silent. Returns bool: filename is empty or exists.`

**Comment by Alexey-T** [comment]
file_open(fn, group=-1, params='')
