### ISSUE TITLE
handling of many tabs

### ISSUE THREAD

**Issue by DerellLicht** [Alexey-T/SynWrite#54]
One difficulty that I had at my last job (which ended a week back) is that tab management was not very flexible with many files open. 

if I had numerous files open (10 or more), the tabs with filenames would just get squeezed smaller and smaller, so that filenames were not readable.  It would be much more usable if the editor would switch to multi-line tabs once a filename didn't fit on its tab any more.

**Comment by Alexey-T** [comment]
I want to to scrollable tabs:like in  ST3 or like some editors. arrows.

**Comment by Alexey-T** [comment]
about 2: can u try plugin Tabs List? it shows left side list of tabs.

**Comment by DerellLicht** [comment]
Okay, I'll definitely try it!

**Comment by Alexey-T** [comment]
Too bad, u didnt realize it:)
