### ISSUE TITLE
Change config storage for plugin hotkeys

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#56]

**Comment by Alexey-T** [comment]
Есть плагин, который вы делали, см слово keymap..

**Comment by kvichans** [comment]
Да, есть, но для Куд. Тот плагин построен вокруг API, которого в Син нет

**Comment by Alexey-T** [comment]
такое todo..

сделать нормальный конфин клавиш. Пока он кривой. запись в synplugins.ini.

**Comment by Alexey-T** [comment]
Начал делать диалог,
как в Cudatext-

![hk-syn](https://cloud.githubusercontent.com/assets/4154978/23755158/e4da6504-04f8-11e7-89b2-d60505e84a97.png)

**Comment by Alexey-T** [comment]
К диалогу будет новый файл конфига- тоже похоже на Куд

**Comment by kvichans** [comment]
Зачем повторять это недоразумение?
Почему не хотите сделать нормальный диалог, хоть отчасти похожий на 
![config hotkeys](https://cloud.githubusercontent.com/assets/7419630/23755881/dd9d221e-04f2-11e7-8bb2-7b5eeb5ee7f9.png)

**Comment by Alexey-T** [comment]
потому что делать такой диалог сложно.
Там у вас колонка snips еще. (Ее делать не нужно в Син.)

**Comment by kvichans** [comment]
Поясняю. Эта колонка появляется только если установлен мой плагин для вызова команда "как снипы". 
"Сложно" - да. Но ваш диалог ужасен

**Comment by Alexey-T** [comment]
done
SynHotkeys.ini (for all lexers)

```
[py:syn_rename_file,run]
name=Rename File
s1=Ctrl+F2
s2=
[py:syn_extract_strings,run]
name=Extract Strings
s1=Ctrl+E
s2=
[1049]
name=Reset Python plugins
s1=F2
s2=
[py:syn_encode,html_deentitize]
name=Encode: HTML Deentitize
s1=Shift+Ctrl+B
s2=
[py:syn_find_in_files,show_dlg]
name=Find in Files: Find in files...
s1=Ctrl+M
s2=
[740]
name=New window
s1=Shift+Ctrl+Alt+N * Ctrl+N * Ctrl+N
s2=
[py:syn_encode,hex_unicode]
name=Encode: Hexadecimal to Unicode
s1=Alt+L
s2=
[py:syn_lint,run]
name=SynLint
s1=
s2=
```

**Comment by kvichans** [comment]
ОК
А что с API? Будет способ узнавать и назначать хоткеи из плагинов?

**Comment by Alexey-T** [comment]
- узнать хоткеи- можно без Api
- задать хоткеи- пока не знаю как делать Api...

**Comment by Alexey-T** [comment]
Уже есть апи для чтения hotkeys

PROC_GET_COMMAND
https://sourceforge.net/p/synwrite/wiki/py%20app-proc%20id/

**Comment by Alexey-T** [comment]
add: PROC_GET_COMMAND_INITIAL
пока написано в файле - бета в /bb.

**Comment by kvichans** [comment]
Я не понял про 
>задать хоткеи- пока не знаю как делать

Можно пойти по такому же пути как в Куд: дать АПИ для вызова того диалога, что у вас уже появляется по `Add key`. Этого будет достаточно.

**Comment by Alexey-T** [comment]
Можно новый issue, pls?

**Comment by Alexey-T** [comment]
+ add: PROC_KEYMAP,
пока описано только в ГХ
https://github.com/Alexey-T/SynWrite/blob/master/Wiki/pyApi/py%20app-proc%20id.md

**Comment by Alexey-T** [comment]
Change storage- solved
другие issue, и про API- в новые ветки, плс.
