### ISSUE TITLE
What is get_caret_xy() when m-carets

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#58]
В файле
[t.txt](https://github.com/Alexey-T/SynWrite/files/770979/t.txt)
делаю два **прямых** выделения, то есть каретки справа
![carets-1](https://cloud.githubusercontent.com/assets/7419630/22883015/15e35320-f1ff-11e6-8c50-5412f8100090.PNG)
Запрашиваю расположение кареток
```
>>> =ed.get_caret_xy()
(3, 3)
>>> =ed.get_carets()
[[7, 0, -6], [9, 3, -6]]
```
Что возвращает `get_caret_xy()`? Может быть этой информацией нельзя пользоваться, когда активно несколько кареток?

**Comment by Alexey-T** [comment]
последнюю каретку. Пол-ся можно,но при м-каретках не нужно

**Comment by kvichans** [comment]
Не понятно. В пример, последняя каретка стоит не в позиции (3, 3), а в (9, 3).
Пока у меня впечатление, что ответы `get_caret_xy()` и `get_carets()` рассогласованы, а значит пользоваться `get_caret_xy()` нельзя, когда несколько кареток.

**Comment by Alexey-T** [comment]
я не помню, может последняя кликнутая каретка. Да не согласованы
