### ISSUE TITLE
Save hotkeys when reinstall plugin from zip-file

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#59]
Выполняю обновление плагина через открытие zip-файла. Все его команды теряют хоткеи.
Если описание команды плагина в SynPlugins.ini не изменилось, то при обновлении нужно сохранить привязанное к этой команде сочетание.

**Comment by Alexey-T** [comment]
Будет решено когда будеит новый конфиг для hotkeys

**Comment by Alexey-T** [comment]
Fixed, 6.36 beta, SynHotkeys.ini
