### ISSUE TITLE
Lines marks are changed even if the corresponding line has not been changed

### ISSUE THREAD

**Issue by ccleaud** [Alexey-T/SynWrite#7]
It happens when:

- replacing text with another (in some condition)
- trimming spaces (this sometimes selects the whole document)

Tested on version: 6.21.2240

Thanks a lot for fixing

**Comment by Alexey-T** [comment]
Do u mean "line states marks"(band on gutter)? if yes, pls, step-to-step, how to repeat bad line marks with "trim spaces", with small text example

**Comment by ccleaud** [comment]
Yes, this is the band on gutter (the one that can take 3 colors).

Here is how you can reproduce:
1. open the attached text file in SynWrite : [xxx.txt](https://github.com/Alexey-T/SynWrite/files/315060/xxx.txt)
2. ensure the caret is at the begining of the file on the very first line
3. ensure you are viewing all characters (like end of line)
4. Menu --> Edit --> Blank operations --> Triml trailing spaces
5. You'll notice the whole file is now selected, every line is colored in the band on gutter ... but lines 3 and 5 shouldn't be changed because they had no trailing spaces
6. You'll also notice the caret has moved to the end of the document ... but I didn't want to change my caret location

I hope this will help you.
Thanks for fixing

File before
![before](https://cloud.githubusercontent.com/assets/7109720/16061660/770aa062-328e-11e6-99ef-26a867e968ab.png)


File after
![after](https://cloud.githubusercontent.com/assets/7109720/16061656/72b00480-328e-11e6-9465-49af255d46e5.png)

**Comment by Alexey-T** [comment]
This is shown OK-tks, will try to work on it

**Comment by Alexey-T** [comment]
fixed: caret-pos restores ok, if no selection; Cannot fix: gutter marks, this is alltext change, sorry
