### ISSUE TITLE
(dlg_custom) new attrs

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#74]
Желательно перенести в Син (если пока нет)c
-    выравнивание вправо для подписей
-    контрол image

**Comment by Alexey-T** [comment]
Todo

**Comment by Alexey-T** [comment]
Done: бета Сина в /bb/

**Comment by kvichans** [comment]
Тестирую...

**Comment by kvichans** [comment]
Почему не работают мои хоткеи?!! Что за ****?

**Comment by kvichans** [comment]
Ну вы даете. Это уже не плевок, в пинок в лицо

**Comment by Alexey-T** [comment]
В 6.36 был изменён конфиг... Может вы не заметили

**Comment by kvichans** [comment]
Я заметил, что надо мной издеваются

**Comment by Alexey-T** [comment]
Я не издевался

**Comment by kvichans** [comment]
Как мне вернуть хоткеи?

**Comment by Alexey-T** [comment]
Т.к конвертера конфига нет, руками

**Comment by kvichans** [comment]
Что РУКАМИ???!!! Вот это и есть издевательство. Я годами набирал хоткеи для удобной работы. А вы их "в мусор" и "начинай сначала"

**Comment by kvichans** [comment]
Работа над обновление ФИФ будет продолжена после восстановления моих хоткеев. Если не будет конвертора, то для _ручного_ переноса могу выслать свои конфиги.

**Comment by Alexey-T** [comment]
Пришлите конфиг плс

**Comment by kvichans** [comment]
Какой файл(ы) передать?

**Comment by Alexey-T** [comment]
Файл получил, набиваю

**Comment by kvichans** [comment]
Не вижу, чтобы в сборке от 03мая,12:19 что-то появилось полезное
- правое выравнивание через type=label,props='1' не работает
- colorpanel - не отображается

Что текстировать?

**Comment by kvichans** [comment]
Правда, `vis` работает.
А что еще?

**Comment by kvichans** [comment]
image - работает

**Comment by Alexey-T** [comment]
- type=image - пока расширенные только props=bool,bool (2 шт)
- right-align - недочет. надо указать props= перед cap=

**Comment by kvichans** [comment]
>только props=bool,bool (2 шт)

Это что?

**Comment by Alexey-T** [comment]
для image пишется "props=bool_center,bool_stretch".
В вики.

**Comment by kvichans** [comment]
Извращение 
>props= перед cap=

помогло

**Comment by Alexey-T** [comment]
Tofix

**Comment by kvichans** [comment]
- `font-color=` - не взялся
- colorpanel - не отображается. А должен?

**Comment by Alexey-T** [comment]
font-color/size/name -Todo.

**Comment by kvichans** [comment]
- colorpanel - и не нужен. Он только для замены линии в Куд ФИФ. Нормально с ----------- будет в Син смотреться.
- font-color - **нужен**
- font-size/font-name - пока не нужны

**Comment by Alexey-T** [comment]
Beta Synw; см новое в истории в вики

**Comment by kvichans** [comment]
Вижу в бете
>"colorpanel", with "props=int_border_size,int_back_color,int_font_color"

А в Куд у colorpanel есть еще один параметр - int_color_border.
Упущен? Специально удален?

**Comment by kvichans** [comment]
ФИФ для Син собрался.

**Comment by Alexey-T** [comment]
Напишу про это так
Supported control types: 
    * button
    * check
    * checkbutton
    * checklistbox
    * checklistview
    * colorpanel, limitation: "props=int_border_size,int_back_color,int_font_color"
    * combo
    * combo_ro
    * edit
    * image, limitation: "props=bool_center,bool_stretch", only bmp/jpg/png images
    * label
    * linklabel
    * listbox
    * listview
    * memo
    * radio
    * radiogroup
    * spinedit
    * tabs

**Comment by Alexey-T** [comment]
right-align label поправлена (порядок).

**Comment by kvichans** [comment]
Потестирую

**Comment by Alexey-T** [comment]
colorpanel поправлен. Порт из Куды

**Comment by kvichans** [comment]
"Потестирую" поставил мимо - это про replace_lines в Куд.
