### ISSUE TITLE
FiF v 1.2.21

### ISSUE THREAD

**Issue by kvichans** [Alexey-T/SynWrite#75]
Бета в ГХ. 
Изменения в history.txt
Потестируйте по возможности. Опубликую позже

**Comment by Alexey-T** [comment]
Image не показывается.

**Comment by Alexey-T** [comment]
- берем папку Лазаруса
- ищем в * строку "procedure init"
- stage1- нашло 28т файлов
- stage2- завис на 0%

**Comment by kvichans** [comment]
Да, забыл добавить картинку в репо. Обновил.
Стресс-тестирование лучше потом

**Comment by Alexey-T** [comment]
Если 50 файлов,работает

**Comment by Alexey-T** [comment]
Делаю релиз Син

**Comment by kvichans** [comment]
Опубликовал - выложил в СФ
