### ISSUE TITLE
"Integrate with Explorer" does not work?

### ISSUE THREAD

**Issue by ElTopo** [Alexey-T/SynWrite#77]
SynWrite version:
6.39.2750 portable (zip file)

OS:
Windows 10 Pro US English
Version: 1703 (OS Build 15063.296)

When I click on "Options --> Integrate with Explorer...", a "SynWrite" dialog prompts me:
Please install plugin "Explorer integration" via Add-ons Manager.

I then click "Options --> Add-ons Manger --> Install..." and install "Explorer Integration", restart SynWrite, but it still prompts me to install the plugin. 

If I click "Options --> Add-ons Manger --> Edit...", "Explorer Integration" shows up as syn_explorer_integration, I can load its __init__.py.

Is there anything I can do to find out what's wrong? Thanks.

**Comment by Alexey-T** [comment]
It is not ok design; need to run

Plugins - Explorer Integration

after plugin installed.

**Comment by ElTopo** [comment]
@Alexey-T Thanks... I didn't notice that there's another menu under "Plugins".

I assume that you will remove the one under "Options"?

**Comment by Alexey-T** [comment]
I maybe rewrite text in this menu.
