### ISSUE TITLE
 auto-complete, block in comment

### ISSUE THREAD

**Issue by ccleaud** [Alexey-T/SynWrite#8]
Can you add 2 checkboxes?
- 1 to prevent popup to be shown when the caret is in a comment
- 1 for the same thing but in a string

Thanks a lot

**Comment by Alexey-T** [comment]
Why popuip shows now in comment, u press CtrlSpace?

**Comment by ccleaud** [comment]
No, I'm just writing text.

What I actually do is only:
1. start SynWrite
2. create a new empty file and save it on my desktop as xxx.sh
3. insert a line echo "add add add"
4. duplicate the line and go to the last character of the string
5. type "add" for instance (No CTRL + SPACE) --> inside the string, the auto-completion list pops up
![2016-06-15 00_05_03- xxx sh - synwrite](https://cloud.githubusercontent.com/assets/7109720/16061364/e3f10920-328c-11e6-8994-73d48c1963ff.png)


I attached my current configuration for auto-completion:
![2016-06-14 23_59_59-options](https://cloud.githubusercontent.com/assets/7109720/16061233/4cb3c7fa-328c-11e6-88bd-c62f927b57d6.png)

Thanks.

**Comment by Alexey-T** [comment]
Maybe ll add such options- but dlg is overloaded, no sure I add it

**Comment by Alexey-T** [comment]
I want to disable it, no option, disable in cmt/strings.
