### ISSUE TITLE
Regular Expression works in search but not in Parser

### ISSUE THREAD

**Issue by joehern** [Alexey-T/SynWrite#83]
I am trying to detect the following Comments in a custom SynWrite lexer.

\# Comment at start of line
 &nbsp;&nbsp;# Comment proceeded by spaces

If I use the expression below in Search it detects both types of comments. The same expression in parser only detects the "Comment at start of line"

^\s*?\#

**Comment by Alexey-T** [comment]
reason: parser skips all spaces. to fix it: in lexer general opts, turn off "skip spaces" [name like it].

**Comment by joehern** [comment]
Thank you.
