### ISSUE TITLE
SynWrite ( version 6.40.2770 ).

### ISSUE THREAD

**Issue by Rewillis** [Alexey-T/SynWrite#84]
Attention: SynWrite staff:
     I have created a small project file, consisting of two small files ( one html file and one .jpg image to be included in the html file ), named "The_Holy_Bible_1.synw-proj."  How do I save this project file to an html file, so that when I upload it to my free web hosting site ( named "infinityFree.net" ), my new web site will appear with the .jpg file included in it?  Thank you ( see Colossians 3:15, for example ) for your help.  Keep in touch.

Sincerely in Christ,
Russell E. Willis
P.S. - Please read Proverbs 23:23.
P.P.S. - I have included a screen capture file, as an attachment, for your consideration.
![capture_synwrite_1](https://user-images.githubusercontent.com/32343216/31437169-645281ba-ae52-11e7-9f24-73020c4f7498.PNG)

**Comment by Alexey-T** [comment]
The Synw project only has 2 files, and to upload them to ftp, use any ftp program, and upload these 2 files. In Synw you can use SynFTP plugin.
