### ISSUE TITLE
pictures for Cud post

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/SynWrite#87]
opt editor
![opt_editor](https://user-images.githubusercontent.com/4154978/46735371-b813bb00-cc9e-11e8-8f06-adc17fb00b15.png)

codetree
![codetree](https://user-images.githubusercontent.com/4154978/46521760-43e5ab80-c889-11e8-81b2-5f6b4aa77f73.png)

toolbar
 
![toolbar](https://user-images.githubusercontent.com/4154978/46522526-ab9cf600-c88b-11e8-84d3-cc2ed3502c83.png)

nav bar
 
 
![nav bar](https://user-images.githubusercontent.com/4154978/46524292-07b64900-c891-11e8-8274-7ef2f361a6f8.png)
 

floating
 
![floating wnd](https://user-images.githubusercontent.com/4154978/46523116-6bd70e00-c88d-11e8-8c9f-f223e72cb911.png)

status - 4 pics
![stat1](https://user-images.githubusercontent.com/4154978/46528301-3554bf80-c89c-11e8-82e4-514e55459a28.png)
![stat2](https://user-images.githubusercontent.com/4154978/46528303-3554bf80-c89c-11e8-878f-8b966d0b3aca.png)
![stat3](https://user-images.githubusercontent.com/4154978/46528304-3554bf80-c89c-11e8-8009-02094d4b13a4.png)
![stat4](https://user-images.githubusercontent.com/4154978/46528305-35ed5600-c89c-11e8-810d-623b1063f000.png)

**Comment by Alexey-T** [comment]
@kvichans Pictures

**Comment by Alexey-T** [comment]
title
![sub_cuda](https://user-images.githubusercontent.com/4154978/46485948-6209c800-c805-11e8-9912-45648b1ffbdc.png)

**Comment by kvichans** [comment]
вот эта 
https://user-images.githubusercontent.com/4154978/46485865-3555b080-c805-11e8-9d59-ad2a8719aa0f.png
недопустимо "мыльная" - похоже при компоновке потерялось "качество"

**Comment by kvichans** [comment]
Оба тул-бара сняты слишком узко - нужно захватить часть редактора, с таким текстом, чтобы было видно про что это. Например, кусок плага с раскраской

**Comment by kvichans** [comment]
Тоже про Дерево. Нужно чтобы на картинке был виден кусок HTML, от которого построено показанное дерево

**Comment by kvichans** [comment]
Картинки "для title" хорошие. Но их можно применить только внутри документа. Для заголовка нужен текст и только текст.

**Comment by Alexey-T** [comment]
иконки накладывать- я не умею так править, у меня редактор простой. по светлому фону видно что это Куд

**Comment by Alexey-T** [comment]
floating- разве размытое не нормално, это же показать просто как float panel смотрится.

**Comment by kvichans** [comment]
1. Дерево получилось хорошо. Только сразу не понятно, почему в нем есть корень Style, а в css его не видно. Скорее всего это из-за того, что таб не именованный - лучше сделать с явным именем файла: `my.css`. 
2. Цветной сайдбар смотрится хорошо. Есть ли цветная тема для тулбара?
3. "Размытый" коллаж никак не подходит
4. Иконки я наложу перед публикацией

**Comment by kvichans** [comment]
Нужны еще несколько снимков для статусбара - показать разные настройки и ситуации: без выделения, с выделением, с каретками, ...

**Comment by Alexey-T** [comment]
>почему в нем есть корень Style, а в css его не видно.

это узел авто генерируется из содержимого. (список стилей)

**Comment by Alexey-T** [comment]
>. Есть ли цветная тема для тулбара?

да, в AddonManager есть раздел toolbartheme.

**Comment by kvichans** [comment]
>  "почему в нем есть корень Style, а в css его не видно."
> это узел авто генерируется из содержимого. (список стилей)

Достаточно сохранить в файл

**Comment by Alexey-T** [comment]
от сохранения дерево не изменится, зачем

**Comment by Alexey-T** [comment]
updated 1st post.
navbar + toolbar + codetree

**Comment by kvichans** [comment]
(если уж переделывать, то до конца)
Тулбар стал оч.хорош. Но рядом с ним виден серый сайдбар - это будет мешать, так как на другом снимке он цветной.
Дерево - ок

**Comment by Alexey-T** [comment]
обновил toolbart (1st post)

**Comment by kvichans** [comment]
:)))
Тулбар - ок
На снимке сайдбара виден серый тулбар - нужно дожать

**Comment by Alexey-T** [comment]
done (1st post)

**Comment by kvichans** [comment]
Сайдбар - ок

**Comment by Alexey-T** [comment]
floating- updated
(1600ms start: slow CPU)

**Comment by kvichans** [comment]
Отмена. Сайдбар не годится. Нужны для него хотя бы два снимка: с заполненной Консолью, с заполненным Поиском - чтобы было понятно, что за кнопки внизу сайдбара.

**Comment by kvichans** [comment]
Коллаж - ок

**Comment by Alexey-T** [comment]
можно один - когда вкл и Поиск и Консоль?

**Comment by Alexey-T** [comment]
![nav bar](https://user-images.githubusercontent.com/4154978/46523500-8f4e8880-c88e-11e8-90c2-7d224a2c4888.png)

**Comment by kvichans** [comment]
У панели Поиск на снимке должна быть видна кнопка Искать - иначе ее назначение не понятно. Да, одного снимка достаточно

**Comment by Alexey-T** [comment]
так?
![nav bar](https://user-images.githubusercontent.com/4154978/46523780-72ff1b80-c88f-11e8-93e9-2250cdb5b264.png)

**Comment by kvichans** [comment]
Ок

**Comment by kvichans** [comment]
Нужны еще статусбары

**Comment by Alexey-T** [comment]
так?
![status](https://user-images.githubusercontent.com/4154978/46524900-e0607b80-c892-11e8-91a9-00931aa40692.png)

**Comment by kvichans** [comment]
это от Суб? если от Куд, то нужно с той же темой что была у баров
нужно с разными настройками и ситуациями (без/с выдел, каретки)

**Comment by Alexey-T** [comment]
лучше:?
![status](https://user-images.githubusercontent.com/4154978/46527762-c32fab00-c89a-11e8-9161-5df6268f72ef.png)

**Comment by Alexey-T** [comment]
лучше?

![status](https://user-images.githubusercontent.com/4154978/46528046-77313600-c89b-11e8-8b96-31b0b5da4051.png)

**Comment by kvichans** [comment]
В таком виде совершенно не понятно. Нужно 4 снимка, чтобы показыватьих друг под другом

**Comment by Alexey-T** [comment]
так?

![stat1](https://user-images.githubusercontent.com/4154978/46528256-ffafd680-c89b-11e8-90bd-3c64601d9231.png)
![stat2](https://user-images.githubusercontent.com/4154978/46528257-ffafd680-c89b-11e8-9eae-2c58fd361801.png)
![stat3](https://user-images.githubusercontent.com/4154978/46528258-ffafd680-c89b-11e8-8fa4-21026acde77a.png)
![stat4](https://user-images.githubusercontent.com/4154978/46528259-00486d00-c89c-11e8-9d5a-47e74d31ab4f.png)

**Comment by kvichans** [comment]
ок

**Comment by Alexey-T** [comment]
все в 1м посте

**Comment by kvichans** [comment]
![sub_statusbar](https://user-images.githubusercontent.com/7419630/47503526-03b78e80-d873-11e8-8daf-cdfb7108196a.png)
![image](https://user-images.githubusercontent.com/7419630/47503933-e6cf8b00-d873-11e8-9195-5a2b8997b504.png)
![1crt](https://user-images.githubusercontent.com/7419630/47504068-2d24ea00-d874-11e8-8406-85dd8f4ea14d.png)
![vert](https://user-images.githubusercontent.com/7419630/47504112-42017d80-d874-11e8-8696-0813469ec378.png)
![4crt](https://user-images.githubusercontent.com/7419630/47504144-5776a780-d874-11e8-8a0f-36eb5b044bcf.png)

![ops-dlg](https://user-images.githubusercontent.com/7419630/47506363-8db62600-d878-11e8-92c3-41a0db103b28.png)

![ops-dlg](https://user-images.githubusercontent.com/7419630/47506425-acb4b800-d878-11e8-8475-71c8e387ee73.png)

![ops-tree](https://user-images.githubusercontent.com/7419630/47506611-1d5bd480-d879-11e8-97bb-27fb3c1f8a5b.png)

![char-map](https://user-images.githubusercontent.com/7419630/47552169-bc7ddc00-d90c-11e8-8edb-6ab76b43053a.png)

![char-map](https://user-images.githubusercontent.com/7419630/47552253-edf6a780-d90c-11e8-94c2-252909287f06.png)
