### ISSUE TITLE
Подсветка выделенных слов a-la Notepad++

### ISSUE THREAD

**Issue by bad-crc** [Alexey-T/SynWrite#88]
В старых версиях была замечательная фича, которая подсвечивала выделенное слово по аналогии с Notepad++. Подскажите, пожалуйста, как вернуть подсветку в новых версиях?

P.S. Cuda не предлагать, т.к. Syn используется в качестве lister плагина для ТС

**Comment by Alexey-T** [comment]
ета фича была вынесена в плагин, ищется в списке по слову Hilite. один из двух.
плагин для Сина.
