### ISSUE TITLE
Decode or Encode URL 

### ISSUE THREAD

**Issue by martbase** [Alexey-T/SynWrite#89]
It would be great to have a plugin/feature that can decode/encode URLs as below

`http%3A%2F%2Fuvviewsoft.com%2Fsynwrite%2F

http://uvviewsoft.com/synwrite/`

**Comment by Alexey-T** [comment]
Plugin "Encode" has commands "URL encode", "URL decode".

**Comment by martbase** [comment]
Thanks, works perfectly (I had been switching to Notepad++ to decode URLs all along!).

I have run into this issue previously where a plugin solved the problem - Issue #85 

Is there a list with details about each plugin somewhere?

**Comment by Alexey-T** [comment]
Currently SynWrite is frozen, I use CudaText. full list is 
https://github.com/Alexey-T/CudaText-registry/tree/master/json

**Comment by martbase** [comment]
Thanks for the link, am sure I can use it as a guide.

I noted some time back that CudaText replaced SynWrite but I'll stick with SynWrite for now unless it becomes incompatible with the latest Windows version. 
I love the editor which feels familiar having worked with the Delphi editor for years and even consider it superior to the later.
The only issue I have encountered is an "Integer overflow" error after which I cannot type or click inside the editor (unable to reproduce as it is rare and over a long duration) - happens when the editor is open for a long time (days) as I simply put my laptop to sleep and continue work from where I last left of and I usually work multiple instances with several tabs open (some instances may be affected and others not!).
