### ISSUE TITLE
[ENHANCEMENT] capitalization effect in lexer

### ISSUE THREAD

**Issue by ccleaud** [Alexey-T/SynWrite#9]
Can you add an option to transform the keyword in the same case it is provided in the lexer configuration?
The goal is to be able to auto convert keywords such "msgbox" to "MsgBox" in VBScript, or "elseif" to "ElseIf".

Thanks a lot.

**Comment by Alexey-T** [comment]
It is here.Help topis is- Coding helpers/ Auto correction of id case
