### ISSUE TITLE
Format date

### ISSUE THREAD

**Issue by jczanfona** [Alexey-T/SynWrite#91]
I want to change the date format when use: Plugin - Insert Time
I've tried putting `DateFmtPlugin=hh:mm dd/mm/aaa` in **Syn.ini** but it hasn't effect.

Thanks in advance.

**Comment by Alexey-T** [comment]
I cannot support this plugin, better switch to CudaText, it also has plugin Insert Time, it can be easily configured via: Options / Settings-plugins / Insert Time.

**Comment by jczanfona** [comment]
Puffff .....
I ❤ SynWrite

Thanks !
