### ISSUE TITLE
Конфликт с wincompose

### ISSUE THREAD

**Issue by pozitronik** [Alexey-T/SynWrite#92]
Обнаружено, что при запущенном syn2.exe попытка скопировать в буфер обмена любую последовательность из окна [WinCompose](https://github.com/samhocevar/wincompose) вызывает в нём сбой. Я оставил [тикет](https://github.com/samhocevar/wincompose/issues/319) в репозитории WinCompose, в котором разработчик предположил, что сбой вызван конфликтом с какой-то программой, также работающей с буфером обмена. Перебором я вышел на SynWrite, но на чьей стороне проблема судить не могу.

Насколько я вижу, для воспроизведения проблемы достаточно просто открытого окна syn2, с настройками по умолчанию

**Comment by Alexey-T** [comment]
Надо отключить слежение за буферном обмена, для Син панели показа клипборда, больше ничего не сделать

И совет перейти на CudaText

**Comment by pozitronik** [comment]
Да, выключение слежения помогло, спасибо.
