### ISSUE TITLE
Формат XML в читабельный вид

### ISSUE THREAD

**Issue by fedorvinogradov** [Alexey-T/SynWrite#93]
Подскажите, пжл, есть возможность в SynWrite привести в порядок (переносы, отступы) файл XML, который выводится в одну строку?

**Comment by Alexey-T** [comment]
Synwrite проект ЗАМОРОЖЕН.
CudaText - переходим на него. в нем да, можно! плагин CudaFormatter + к нему форматтеры для xml.
Plugins / addon manager / install.
